# Generated by Django 4.1.1 on 2022-11-17 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lends', '0003_alter_lend_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lend',
            name='assetReceiver',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lend',
            name='dateReturn',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='lend',
            name='status',
            field=models.IntegerField(choices=[(1, 'Berjalan'), (2, 'Ditutup')], default=1, editable=False),
        ),
    ]
