# Generated by Django 4.1.1 on 2022-11-04 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendors', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.IntegerField(choices=[(1, 'Normal'), (2, 'Perlu diperiksa'), (3, 'Diperbaiki'), (4, 'Dipinjam'), (5, 'Rusak')], default=1)),
                ('merk', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('datePurchased', models.DateField(auto_now_add=True)),
                ('warrantyYears', models.IntegerField()),
                ('usefulLife', models.IntegerField()),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='vendors.vendor')),
            ],
        ),
    ]
