# Generated by Django 4.1.1 on 2022-11-05 12:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='datePurchased',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
