# Generated by Django 4.1.1 on 2022-11-17 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='lastInspection',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
    ]
