# Generated by Django 4.1.1 on 2022-11-05 12:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
        ('assets', '0002_alter_asset_datepurchased'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='datePurchased',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='asset',
            name='merk',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='asset',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='vendors.vendor'),
        ),
    ]
