# Generated by Django 4.1.1 on 2022-11-24 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_asset_lastinspection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.IntegerField(choices=[(1, 'Normal'), (2, 'Perlu diperiksa'), (3, 'Diperbaiki'), (4, 'Dipinjam'), (5, 'Rusak')], default=1, editable=False),
        ),
    ]
