# Generated by Django 4.1.1 on 2022-11-24 11:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_alter_asset_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='lastInspection',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2022, 11, 24, 11, 16, 55, 632851, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
