# Generated by Django 4.1.1 on 2022-11-18 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inspections', '0007_alter_inspection_ongoing'),
        ('assets', '0002_asset_lastinspection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('cost', models.FloatField()),
                ('date', models.DateField(auto_now_add=True)),
                ('staffName', models.CharField(editable=False, max_length=50)),
                ('maintain', models.BooleanField(editable=False, null=True)),
                ('asset', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='assets.asset')),
                ('inspection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inspections.inspection')),
                ('staff', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
