# Generated by Django 4.1.1 on 2022-11-20 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenances', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='dateFinished',
            field=models.DateField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='date',
            field=models.DateField(editable=False, null=True),
        ),
    ]
