# Generated by Django 4.1.1 on 2022-11-20 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenances', '0002_maintenance_datefinished_alter_maintenance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='assetWorth',
            field=models.FloatField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maintenance',
            name='status',
            field=models.IntegerField(choices=[(1, 'Approved'), (0, 'Rejected'), (2, 'Waiting for approval')], default=2, editable=False),
        ),
    ]
