# Generated by Django 4.1.1 on 2022-11-20 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenances', '0003_maintenance_assetworth_maintenance_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenance',
            name='status',
        ),
    ]
