# Generated by Django 4.1.1 on 2022-11-20 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenances', '0004_remove_maintenance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='dateStart',
            field=models.DateField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
