# Generated by Django 4.1.1 on 2022-11-13 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0002_alter_inspection_inspector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
