# Generated by Django 4.1.1 on 2022-11-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0003_alter_inspection_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='photo',
            field=models.ImageField(default=3, upload_to='img/inspections/'),
            preserve_default=False,
        ),
    ]
