# Generated by Django 4.1.1 on 2022-11-14 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0006_inspection_ongoing_alter_inspection_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='ongoing',
            field=models.BooleanField(blank=True, default=False, editable=False, null=True),
        ),
    ]
